code:
  name: dkube-examples
  url: https://github.com/oneconvergence/dkube-examples.git
  branch: tensorflow
  private: false
datasets:
  - name: mnist
    source: pub_url
    url: https://dkube.s3.amazonaws.com/datasets/small_mnist/mnist.pkl.gz
models:
  - name: mnist

arguments:
  code: dkube-examples
  run_script: python mnist/train.py
  transformer_script: mnist/transformer.py
  dataset: mnist
  dataset_mount_path: /mnist
  model: mnist
  model_mount_path: /model
